--Q1. What is the total revenue generated by male vs. female customers?

select gender,SUM(purchase_amount) as revenvue
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select AVG(purchase_amount)
from customer);

--Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,AVG(review_rating) as average_review_rating 
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,ROUND(AVG(purchase_amount),2) as average_purchase
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
order by AVG(purchase_amount);

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
COUNT(*) total_customers,
ROUND(AVG(purchase_amount),2) as average_spend,
SUM(purchase_amount) as total_revenue
from customer
group by subscription_status
order by SUM(purchase_amount) desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
ROUND (100 * SUM (CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) /COUNT (*),2) as discount_rate
from customer 
group by item_purchased 
order by discount_rate desc 
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)

SELECT customer_segment,
       COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category?

WITH product_sales AS (
    SELECT category,
           item_purchased,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(*) DESC
           ) AS rn
    FROM customer
    GROUP BY category, item_purchased
)

SELECT category,
       item_purchased,
       purchase_count
FROM product_sales
WHERE rn <= 3
ORDER BY category, purchase_count DESC;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as repeat_buyers 
from customer 
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 

select age_group,
SUM (purchase_amount) as total_revenue
from customer 
group by age_group 
order by total_revenue desc;
